{
 "title": "SolarBoat data",
 "time": { "from": "1970-01-01T01:00:01.908Z", "to": "1970-01-01T01:00:18.680Z" },
 "panels": [
  {
   "title": "IMU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "IMU data",
     "type": "trend",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID, ax, ay, az, gx, gy, gz, mx, my, mz, heading, pitch, roll\r\nFROM IMU_data\r\nORDER BY ID ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Ultrasonic Full",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ultrasoon digital data",
     "type": "trend",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 0 AND 11884\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon & IMU digital data",
     "type": "trend",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID, height, foil, pitch, roll\r\nFROM Digital_ultrasoonIMU\r\nWHERE ID BETWEEN 0 AND 11884\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon & IMU analog data",
     "type": "trend",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID, height, foil, pitch, roll\r\nFROM Analog_ultrasoonIMU\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon analog data",
     "type": "trend",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nORDER BY ID ASC;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Ultasonic by Setup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ultrasoon digital data Reading 1",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 110 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 0 AND 1512\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon analog data Reading 1",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 110 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 0 AND 1512\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon digital data Reading 2",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 122 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 1532 AND 3071\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon analog data Reading 2",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 122 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 3026 AND 4565\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon digital data Reading 3",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 218 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 3091 AND 4555\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon analog data Reading 3",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 218 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 6005 AND 7537\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon digital data Reading 4",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 230 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 4556 AND 5985\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon analog data Reading 4",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 230 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 9021 AND 10451\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon digital data Reading 5",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 242 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 6006 AND 7528\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon analog data Reading 5",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 242 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 12098 AND 13620\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon digital data Reading 6",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 254 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 7548 AND 9151\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon analog data Reading 6",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 254 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 15056 AND 16659\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon digital data Reading 7",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 266 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 9171 AND 11884\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon analog data Reading 7",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 266 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 18017 AND 20730\r\nORDER BY ID ASC;\r\n"
      }
     ]
    },
    {
     "title": "Ultrasoon digital data Reading 8",
     "type": "trend",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 278 },
     "targets": [
      {
       "dataset": "IMU",
       "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 11904 AND 13871\r\nORDER BY ID ASC;\r\n"
      }
     ]
    }
   ]
  },
  { "title": "Ultrasonic Zoomed in", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Zoomed in Reading 1 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Digital_data\r\nWHERE ID BETWEEN 0 AND 500\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 1 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 0 AND 500\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 1 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Analog_data\r\nWHERE ID BETWEEN 0 AND 500\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 1 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 0 AND 500\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 2 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Digital_data\r\nWHERE ID BETWEEN 1532 AND 2032\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 2 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 1532 AND 2032\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 2 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Analog_data\r\nWHERE ID BETWEEN 3026 AND 3526\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 2 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 3026 AND 3526\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 3 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Digital_data\r\nWHERE ID BETWEEN 3091 AND 3591\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 3 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 3091 AND 3591\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 3 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Analog_data\r\nWHERE ID BETWEEN 6005 AND 6505\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 3 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 6005 AND 6505\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 4 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Digital_data\r\nWHERE ID BETWEEN 4575 AND 5075\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 4 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 4575 AND 5075\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 4 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 40 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Analog_data\r\nWHERE ID BETWEEN 9021 AND 9521\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 4 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 40 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 9021 AND 9521\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 5 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 52 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Digital_data\r\nWHERE ID BETWEEN 6006 AND 6506\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 5 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 6006 AND 6506\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 5 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 52 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Analog_data\r\nWHERE ID BETWEEN 12098 AND 12598\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 5 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 52 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 12098 AND 12598\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 6 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 64 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Digital_data\r\nWHERE ID BETWEEN 7548 AND 8148\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 6 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 64 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 7548 AND 8048\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 6 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 64 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Analog_data\r\nWHERE ID BETWEEN 15056 AND 15556\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 6 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 64 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 15056 AND 15556\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 7 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 76 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Digital_data\r\nWHERE ID BETWEEN 9171 AND 9671\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 7 digital",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 76 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Digital_data\r\nWHERE ID BETWEEN 9171 AND 9671\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 7 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 76 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) AS mean_last_20\r\nFROM Analog_data\r\nWHERE ID BETWEEN 18017 AND 18517\r\nORDER BY ID ASC;\r\n"
    }
   ]
  },
  {
   "title": "Zoomed in Reading 7 analog",
   "type": "trend",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 76 },
   "targets": [
    {
     "dataset": "IMU",
     "rawSql": "SELECT\r\n  ID,\r\n  counts * 0.0859655832 AS mm,\r\n  AVG(counts) OVER (\r\n      ORDER BY ID\r\n      ROWS BETWEEN 9 PRECEDING AND CURRENT ROW\r\n  ) * 0.0859655832 AS mean_mm\r\nFROM Analog_data\r\nWHERE ID BETWEEN 18017 AND 18517\r\nORDER BY ID ASC;\r\n"
    }
   ]
  }
 ]
}